name = "my-site"
pages_build_output_dir = "dist"
compatibility_date = "2024-06-23"

[env.production]
compatibility_date = "2024-06-23"

[env.production.vars]
NODE_VERSION = "22.9.0"
BUN_VERSION = "1.1.18"
